/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author SM TRADERS
 */
public class Calculator1 extends javax.swing.JFrame {

    public Calculator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sci-Calculator");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 272, 52));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setText("2");
        jButton1.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setText("3");
        jButton2.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 255, 255));
        jButton3.setText("1");
        jButton3.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 255, 255));
        jButton4.setText("4");
        jButton4.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 255, 255));
        jButton5.setText("6");
        jButton5.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 255, 255));
        jButton6.setText("5");
        jButton6.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton6.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jButton7.setBackground(new java.awt.Color(0, 255, 255));
        jButton7.setText("7");
        jButton7.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton7.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton7.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButton8.setBackground(new java.awt.Color(0, 255, 255));
        jButton8.setText("8");
        jButton8.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton8.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton8.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jButton9.setBackground(new java.awt.Color(0, 255, 255));
        jButton9.setText("9");
        jButton9.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton9.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton9.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jButton10.setBackground(new java.awt.Color(0, 255, 255));
        jButton10.setText("+");
        jButton10.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jButton11.setBackground(new java.awt.Color(0, 255, 255));
        jButton11.setText("X");
        jButton11.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton11.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton11.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jButton12.setBackground(new java.awt.Color(0, 255, 255));
        jButton12.setText("/");
        jButton12.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton12.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton12.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jButton13.setBackground(new java.awt.Color(0, 255, 255));
        jButton13.setText("0");
        jButton13.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton13.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton13.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jButton14.setBackground(new java.awt.Color(0, 255, 255));
        jButton14.setText("-");
        jButton14.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton14.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton14.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        jButton15.setBackground(new java.awt.Color(0, 255, 255));
        jButton15.setText("AC");
        jButton15.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jButton16.setBackground(new java.awt.Color(0, 255, 255));
        jButton16.setText("=");
        jButton16.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jButton17.setBackground(new java.awt.Color(0, 255, 255));
        jButton17.setText(".");
        jButton17.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton17.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton17.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jButton18.setBackground(new java.awt.Color(0, 255, 255));
        jButton18.setText("sin");
        jButton18.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jButton19.setBackground(new java.awt.Color(0, 255, 255));
        jButton19.setText("cos");
        jButton19.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jButton20.setBackground(new java.awt.Color(0, 255, 255));
        jButton20.setText("tan");
        jButton20.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jButton21.setBackground(new java.awt.Color(0, 0, 0));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Shift");
        jButton21.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jButton22.setBackground(new java.awt.Color(0, 0, 0));
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("M+");
        jButton22.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jButton23.setBackground(new java.awt.Color(0, 0, 0));
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("M-");
        jButton23.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jButton24.setBackground(new java.awt.Color(0, 0, 0));
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("Mode");
        jButton24.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jButton25.setBackground(new java.awt.Color(0, 0, 0));
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("x^2");
        jButton25.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton26.setBackground(new java.awt.Color(0, 0, 0));
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("ln");
        jButton26.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jButton27.setBackground(new java.awt.Color(0, 0, 0));
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("log");
        jButton27.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jButton28.setBackground(new java.awt.Color(0, 0, 0));
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("sqrt");
        jButton28.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jButton29.setBackground(new java.awt.Color(0, 0, 0));
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("x!");
        jButton29.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jButton30.setBackground(new java.awt.Color(0, 0, 0));
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("HEX");
        jButton30.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jButton31.setBackground(new java.awt.Color(0, 0, 0));
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("BIN");
        jButton31.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jButton32.setBackground(new java.awt.Color(0, 0, 0));
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("OCT");
        jButton32.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton32.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jButton32ComponentHidden(evt);
            }
        });
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jButton33.setBackground(new java.awt.Color(0, 0, 0));
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("mcr");
        jButton33.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton33.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jButton33ComponentHidden(evt);
            }
        });
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jButton34.setBackground(new java.awt.Color(0, 0, 0));
        jButton34.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("e");
        jButton34.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jButton35.setBackground(new java.awt.Color(0, 0, 0));
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("M");
        jButton35.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jButton36.setBackground(new java.awt.Color(0, 0, 0));
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("DEL");
        jButton36.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jButton37.setBackground(new java.awt.Color(0, 0, 0));
        jButton37.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("D");
        jButton37.setPreferredSize(new java.awt.Dimension(60, 25));
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, 15));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 290, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 10));

        getAccessibleContext().setAccessibleDescription("Sci-fi");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "1");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "3");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "5");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "6");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (trignocheck == 0) {
            if (zerockeck == 0) {
                this.jTextField1.setText("");
                zerockeck = 1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText() + "0");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        r = '/';
        pointckeck = 0;
        try {
            n1 = Double.parseDouble(this.jTextField1.getText());
        } catch (NumberFormatException e) {
            this.jTextField1.setText("");
        }
        jTextField1.setText("");
        if (n2 == 0) {
            chk = 1;
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        r = 'X';
        pointckeck = 0;
        try {
            n1 = Double.parseDouble(this.jTextField1.getText());
        } catch (NumberFormatException e) {
            this.jTextField1.setText("");
        }
        jTextField1.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        r = '+';
        pointckeck = 0;
        try {
            n1 = Double.parseDouble(this.jTextField1.getText());
        } catch (NumberFormatException e) {
            this.jTextField1.setText("");
        }
        jTextField1.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        r = '-';
        pointckeck = 0;
        try {
            n1 = Double.parseDouble(this.jTextField1.getText());
        } catch (NumberFormatException e) {
            this.jTextField1.setText("");
        }
        jTextField1.setText("");

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
//mcr=0;
        r = '"';
        n1 = 0;
        n2 = 0;
        result = 0;
        trignocheck = 0;
        zerockeck = 0;
        pointckeck = 0;
        this.jTextField1.setText("0");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        pointckeck = 0;
        if (this.jTextField1.getText() == "") {
            n1 = Double.parseDouble(this.jTextField1.getText());

        }
        if (turn == 0) {
            n2 = Double.parseDouble(this.jTextField1.getText());
        }

        if (r == '/') {
            if (chk == 1) {
                this.jTextField1.setText("Undefined");
            }
            result = n1 / n2;
        } else if (r == 'X') {
            result = n1 * n2;
        } else if (r == '+') {
            result = n1 + n2;
        } else if (r == '-') {
            result = n1 - n2;
        } else if (r == 's' && modecount == 0) {
            n = jTextField1.getText().substring(3);

            try {
                result = Math.sin(Double.parseDouble(n)) * 180 / Math.PI;

            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 's' && modecount == 1) {
            n = jTextField1.getText().substring(3);

            try {
                result = Math.sin(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == '1' && modecount == 0) {
            n = jTextField1.getText().substring(4);
            try {
                result = Math.asin(Double.parseDouble(n)) * 180 / Math.PI;
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == '1' && modecount == 1) {
            n = jTextField1.getText().substring(4);
            try {
                result = Math.asin(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 'c' && modecount == 0) {
            n = this.jTextField1.getText().substring(3);
            try {
                result = Math.cos(Double.parseDouble(n)) * 180 / Math.PI;
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 'c' && modecount == 1) {
            n = this.jTextField1.getText().substring(3);
            try {
                result = Math.cos(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == '2' && modecount == 0) {
            n = jTextField1.getText().substring(4);
            try {
                result = Math.acos(Double.parseDouble(n)) * 180 / Math.PI;
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == '2' && modecount == 1) {
            n = jTextField1.getText().substring(4);
            try {
                result = Math.acos(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
        } else if (r == 't' && modecount == 0) {
            n = this.jTextField1.getText().substring(3);
            try {
                result = Math.tan(Double.parseDouble(n)) * 180 / Math.PI;
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 't' && modecount == 1) {
            n = this.jTextField1.getText().substring(3);
            try {
                result = Math.tan(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == '3' && modecount == 0) {
            n = this.jTextField1.getText().substring(4);
            try {
                result = Math.atan(Double.parseDouble(n)) * 180 / Math.PI;
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == '3' && modecount == 1) {
            n = this.jTextField1.getText().substring(4);
            try {
                result = Math.atan(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 'q') {
            try {
                square = Double.parseDouble(jTextField1.getText());
            } catch (NumberFormatException e) {
                jTextField1.setText("");
            }
            result = square * square;
            turn = 0;
        } else if (r == 'l') {
            n = jTextField1.getText().substring(3);
            try {
                result = Math.log(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 'g') {
            n = jTextField1.getText().substring(3);
            try {
                result = Math.log10(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 'r') {
            n = jTextField1.getText().substring(4);
            try {
                result = Math.sqrt(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 'e') {
            n = jTextField1.getText().substring(2);
            try {
                result = Math.exp(Double.parseDouble(n));
            } catch (NumberFormatException e) {
                this.jTextField1.setText("");
            }
            turn = 0;
        } else if (r == 'f') {
            double fact = 1;
            n = this.jTextField1.getText().substring(2);
            num1 = Integer.parseInt(n);
            for (int i = 1; i <= num1; i++) {
                fact = fact * i;
            }
            result = fact;
            check = 0;
            turn = 0;
        }
        if (ansckeck == 0) {
            this.jTextField1.setText("" + result);
        }
        if (r == 'h') {
            int num;
            String binery, inputnumber;
            inputnumber = jTextField1.getText();
            num = Integer.parseInt(inputnumber);
            binery = Integer.toHexString(num);
            jTextField1.setText(binery);
            ansckeck = 0;
        } else if (r == 'b') {
            /*num=Integer.parseInt(n);
    //num=this.jTextField1.setText(this.jTextField1.getText());
    //jTextField1.setText(""+Integer.toBinaryString(num));
     des=Integer.toBinaryString(num);
    jTextField1.setText(des);
    turn=0;*/
            int num;
            String binery, inputnumber;
            inputnumber = jTextField1.getText();
            num = Integer.parseInt(inputnumber);
            binery = Integer.toBinaryString(num);
            jTextField1.setText(binery);
            ansckeck = 0;
        } else if (r == 'o') {
            int num;
            String binery, inputnumber;
            inputnumber = jTextField1.getText();
            num = Integer.parseInt(inputnumber);
            binery = Integer.toOctalString(num);
            jTextField1.setText(binery);
            ansckeck = 0;
        }

        check = 1;

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if (check == 1) {
            check = 0;
            this.jTextField1.setText("");
        }
        if (pointckeck == 0) {
            jTextField1.setText(jTextField1.getText() + ".");
        }
        pointckeck = 1;
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        check = 0;
        trignocheck = 1;
        if (count == 0) {
            this.jTextField1.setText("sin");
            r = 's';
            turn = 1;
        } else {
            this.jTextField1.setText("asin");
            r = '1';
            turn = 1;
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        if (count == 0) {
            this.jButton18.setText("sin-1");
            this.jButton19.setText("cos-1");
            this.jButton20.setText("tan-1");
            count = 1;
        } else if (count == 1) {
            this.jButton18.setText("sin");
            this.jButton19.setText("cos");
            this.jButton20.setText("tan");
            count = 0;
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        check = 0;
        trignocheck = 1;
        if (count == 0) {
            this.jTextField1.setText("cos");
            r = 'c';
            turn = 1;
        } else if (count == 1) {
            this.jTextField1.setText("acos");
            r = '2';
            turn = 1;
        }

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        check = 0;
        trignocheck = 1;
        if (count == 0) {
            this.jTextField1.setText("tan");
            r = 't';
            turn = 1;
        }
        if (count == 1) {
            this.jTextField1.setText("atan");
            r = '3';
            turn = 1;
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        r = 'q';
        turn = 1;
        this.jTextField1.setText("");
        this.jTextField1.setText(this.jTextField1.getText() + "");
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        trignocheck = 1;
        check = 0;
        r = 'l';
        turn = 1;
        this.jTextField1.setText("");
        this.jTextField1.setText(this.jTextField1.getText() + "log");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        trignocheck = 1;
        check = 0;
        r = 'g';
        turn = 1;
        this.jTextField1.setText("");
        this.jTextField1.setText(this.jTextField1.getText() + "log");
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        trignocheck = 1;
        check = 0;
        r = 'r';//square root
        turn = 1;
        this.jTextField1.setText("");
        this.jTextField1.setText(this.jTextField1.getText() + "sqrt");
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton32ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton32ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ComponentHidden

    private void jButton33ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton33ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ComponentHidden

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        this.jTextField1.setText("");
        mcr = 0;
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        trignocheck = 1;
        check = 0;
        r = 'e';
        turn = 1;
        this.jTextField1.setText("");
        this.jTextField1.setText(this.jTextField1.getText() + "e^");
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        ansckeck = 1;
        this.jTextField1.setText("");
        r = 'h';
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        trignocheck = 1;
        check = 0;
        turn = 1;
        r = 'f';
        this.jTextField1.setText("");
        this.jTextField1.setText(this.jTextField1.getText() + "x!");
//jTextField1.getText();
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        ansckeck = 1;
        this.jTextField1.setText("");
        r = 'b';

    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        ansckeck = 1;
        this.jTextField1.setText("");
        r = 'o';

    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        mcr = result + mcr;
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        mcr = mcr - result;
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        this.jTextField1.setText("" + mcr);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        this.jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getText().length() - 1));
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        if (modecount == 0) {
            this.jButton37.setText("R");
            modecount = 1;
        } else if (modecount == 1) {
            this.jButton37.setText("D");
            modecount = 0;
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator1().setVisible(true);
            }
        });
    }
    int count = 0;//control Shift button 
    int modecount = 0;
    private double result;
    private double n1, square;//Veriable for first number
    private double n2;//variable for second number
    private char r;
    private int chk = 0;//if divede by infinity
    private int check = 0;//this is for removing result on screen when enter new number
    int turn = 0;//for Trignometric functions
    private String n, des;
    int pointckeck = 0;//cannot use point more then one time
    int zerockeck = 0, num1;//use for dislplay 0 everytime in the TextField
    private int trignocheck = 0;//used for display trignometric functions on TextField1 like: sin 12, asin 60...
    double mcr = 0;//control M+,M-,M button
    int ansckeck = 0;//controls the binery conversion answere and other functions answere
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
