/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author SM TRADERS
 */
public class simplecalculator extends javax.swing.JFrame {

    /**
     * Creates new form simplecalculator
     */
    public simplecalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(51, 51, 0));

        jButton8.setBackground(new java.awt.Color(102, 255, 0));
        jButton8.setText("8");
        jButton8.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton8.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 255, 0));
        jButton9.setText("9");
        jButton9.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton9.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 255, 0));
        jButton10.setText("+");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(102, 255, 0));
        jButton11.setText("X");
        jButton11.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton11.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(102, 255, 0));
        jButton12.setText("/");
        jButton12.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton12.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(102, 255, 0));
        jButton13.setText("0");
        jButton13.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton13.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(102, 255, 0));
        jButton14.setText("-");
        jButton14.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton14.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(102, 255, 0));
        jButton16.setText("=");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(102, 255, 0));
        jButton17.setText(".");
        jButton17.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton17.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setText("2");
        jButton1.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 0));
        jButton2.setText("3");
        jButton2.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 255, 0));
        jButton3.setText("1");
        jButton3.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 255, 0));
        jButton4.setText("4");
        jButton4.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 255, 0));
        jButton5.setText("6");
        jButton5.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 255, 0));
        jButton6.setText("5");
        jButton6.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 255, 0));
        jButton7.setText("7");
        jButton7.setMaximumSize(new java.awt.Dimension(41, 23));
        jButton7.setMinimumSize(new java.awt.Dimension(41, 23));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(0, 255, 255));
        jButton15.setText("AC");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton36.setBackground(new java.awt.Color(0, 0, 0));
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("DEL");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setBackground(new java.awt.Color(0, 0, 0));
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("sci-fic");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton36)
                    .addComponent(jButton37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        r='+';
        pointckeck=0;
        try{
            n1=Double.parseDouble(this.jTextField1.getText());
        }catch(NumberFormatException e){
            this.jTextField1.setText("");
        }
        jTextField1.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        r='X';
        pointckeck=0;
        try{
            n1=Double.parseDouble(this.jTextField1.getText());
        }catch(NumberFormatException e){
            this.jTextField1.setText("");
        }
        jTextField1.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        r='/';
        pointckeck=0;
        try{
            n1=Double.parseDouble(this.jTextField1.getText());
        }catch(NumberFormatException e){
            this.jTextField1.setText("");
        }
        jTextField1.setText("");
        if(n2==0)
        chk=1;
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"0");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        r='-';
        pointckeck=0;
        try{
            n1=Double.parseDouble(this.jTextField1.getText());
        }catch(NumberFormatException e){
            this.jTextField1.setText("");
        }
        jTextField1.setText("");

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        pointckeck=0;
        if (this.jTextField1.getText()==""){
            n1=Double.parseDouble(this.jTextField1.getText());

        }
        if(turn==0)
        n2=Double.parseDouble(this.jTextField1.getText());

        if(r=='/')
        {if(chk==1)
            this.jTextField1.setText("Undefined");
            result=n1/n2;}
        else if(r=='X')
        {result=n1*n2;}
        else if(r=='+')
        {result=n1+n2;}
        else if(r=='-')
        {result=n1-n2;}
        else if(r=='s'&&modecount==0)
        {
            n=jTextField1.getText().substring(3);

            try{
                result=Math.sin(Double.parseDouble(n))*180/Math.PI;

            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='s'&&modecount==1)
        {
            n=jTextField1.getText().substring(3);

            try{
                result=Math.sin(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='1'&&modecount==0)
        { n=jTextField1.getText().substring(4);
            try{
                result=Math.asin(Double.parseDouble(n))*180/Math.PI;
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='1'&&modecount==1)
        { n=jTextField1.getText().substring(4);
            try{
                result=Math.asin(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='c'&&modecount==0){
            n=this.jTextField1.getText().substring(3);
            try{
                result=Math.cos(Double.parseDouble(n))*180/Math.PI;
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='c'&&modecount==1){
            n=this.jTextField1.getText().substring(3);
            try{
                result=Math.cos(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='2'&&modecount==0){
            n=jTextField1.getText().substring(4);
            try{
                result=Math.acos(Double.parseDouble(n))*180/Math.PI;
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='2'&&modecount==1){
            n=jTextField1.getText().substring(4);
            try{
                result=Math.acos(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
        }
        else if(r=='t'&&modecount==0){
            n=this.jTextField1.getText().substring(3);
            try{
                result=Math.tan(Double.parseDouble(n))*180/Math.PI;
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='t'&&modecount==1){
            n=this.jTextField1.getText().substring(3);
            try{
                result=Math.tan(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='3'&&modecount==0){
            n=this.jTextField1.getText().substring(4);
            try{
                result=Math.atan(Double.parseDouble(n))*180/Math.PI;
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='3'&&modecount==1){
            n=this.jTextField1.getText().substring(4);
            try{
                result=Math.atan(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='q'){
            try{
                square=Double.parseDouble(jTextField1.getText());
            }catch(NumberFormatException e){
                jTextField1.setText("");
            }
            result=square*square;
            turn=0;
        }
        else if(r=='l'){
            n=jTextField1.getText().substring(3);
            try{
                result=Math.log(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='g'){
            n=jTextField1.getText().substring(3);
            try{
                result=Math.log10(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='r'){
            n=jTextField1.getText().substring(4);
            try{
                result=Math.sqrt(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='e'){
            n=jTextField1.getText().substring(2);
            try{
                result=Math.exp(Double.parseDouble(n));
            }catch(NumberFormatException e){
                this.jTextField1.setText("");
            }
            turn=0;
        }
        else if(r=='f'){
            int fact=1;
            n=this.jTextField1.getText().substring(2);
            num1=Integer.parseInt(n);
            for(int i=1;i<=num1;i++){
                fact=fact*i;
            }
            result=fact;
            check=0;
            turn=0;
        }
        if(ansckeck==0)
        this.jTextField1.setText(""+result);
        if(r=='h'){
            int num;
            String binery,inputnumber;
            inputnumber=jTextField1.getText();
            num=Integer.parseInt(inputnumber);
            binery=Integer.toHexString(num);
            jTextField1.setText(binery);
            ansckeck=0;
        }
        else if(r=='b'){
            /*num=Integer.parseInt(n);
            //num=this.jTextField1.setText(this.jTextField1.getText());
            //jTextField1.setText(""+Integer.toBinaryString(num));
            des=Integer.toBinaryString(num);
            jTextField1.setText(des);
            turn=0;*/
            int num;
            String binery,inputnumber;
            inputnumber=jTextField1.getText();
            num=Integer.parseInt(inputnumber);
            binery=Integer.toBinaryString(num);
            jTextField1.setText(binery);
            ansckeck=0;
        }
        else if(r=='o'){
            int num;
            String binery,inputnumber;
            inputnumber=jTextField1.getText();
            num=Integer.parseInt(inputnumber);
            binery=Integer.toOctalString(num);
            jTextField1.setText(binery);
            ansckeck=0;
        }

        check=1;
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(pointckeck==0)
        jTextField1.setText(jTextField1.getText()+".");
        pointckeck=1;
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"3");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"1");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"6");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"5");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(check==1)
        {check=0;
            this.jTextField1.setText("");}
        if(trignocheck==0){
            if(zerockeck==0){
                this.jTextField1.setText("");
                zerockeck=1;
            }
        }
        this.jTextField1.setText(this.jTextField1.getText()+"7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        //mcr=0;
        r='"';  
        n1=0;n2=0;result=0;
        trignocheck=0;
        zerockeck=0;
        pointckeck=0;
        this.jTextField1.setText("0");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        this.jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getText().length() - 1));
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
       Calculator1 ob3=new Calculator1();
       ob3.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton37ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simplecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simplecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simplecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simplecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simplecalculator().setVisible(true);
            }
        });
    }
int count=0;//control Shift button 
    int modecount=0;
    private double result;
private double n1,square;//Veriable for first number
private double n2;//variable for second number
private char r;
private int chk=0;//if divede by infinity
private int check=0;//this is for removing result on screen when enter new number
int turn=0;//for Trignometric functions
private String n,des;
int pointckeck=0;//cannot use point more then one time
int zerockeck=0,num1;//use for dislplay 0 everytime in the TextField
private int trignocheck=0;//used for display trignometric functions on TextField1 like: sin 12, asin 60...
double mcr=0;
int ansckeck=0;//controls the binery conversion answere and other functions answere
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
